### ISSUE TITLE
[DPP-56] GenProcess doesn't drain its mailbox properly

### ISSUE THREAD

**Issue by qnikst** [haskell-distributed/distributed-process-platform#124]
[Imported from JIRA. Reported by Tim Watson [Administrator] @hyperthunk)  as [DPP-56](https://cloud-haskell.atlassian.net/browse/DPP-56) on 2013-01-14 22:06:57]
If you pass `infoHandlers = []` then no info messages are consumed and the process' mailbox will just keep on growing. So a standard handler that applies the default policy is probably a good idea.

estimate: 10 mins

**Comment by hyperthunk** [comment]
Fixed in d78185e6
